apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: gloo-test
data:
  config.yaml: |
    domain: custom
    descriptors:
      - key: generic_key
        value: slowpath
        rate_limit:
          requests_per_unit: 2
          unit: minute
      - key: ratelimitkey
        descriptors:
          - key: path
            rate_limit:
              requests_per_unit: 100
              unit: minute
      - key: plan
        value: BASIC
        descriptors:
          - key: account
            rate_limit:
              unit: minute
              requests_per_unit: 1
      - key: plan
        value: PLUS
        descriptors:
          - key: account
            rate_limit:
              unit: minute
              requests_per_unit: 2
